import {
  AlertTriangle, BarChart3, Bell, BriefcaseBusiness, CalendarDays, CheckCircle2, ChevronRight,
  ClipboardCheck, Clock3, Download, FileCheck2, Filter, LayoutDashboard, LockKeyhole,
  Mail, Moon, MoreVertical, Phone, Search, Settings as SettingsIcon, ShieldCheck, Sun,
  UserRound, Workflow,
} from 'lucide-react'
import { useEffect, useMemo, useState, type ReactNode } from 'react'
import './App.css'
import { getAnalytics, getEvents, getExceptions, listCases, postJson, type AnalyticsSummary, type BackendEvent } from './api'
import { BarsH } from './components/BarsH'
import { Donut } from './components/Donut'
import { Gauge } from './components/Gauge'
import { Heatmap } from './components/Heatmap'
import { LineTrend } from './components/LineTrend'
import { StatTile } from './components/StatTile'
import { demoCases } from './data/demoCases'
import type { BackendCase, CaseStage, LoanCase, RiskBand } from './model/types'
import { buildDashboardMetrics, filterCases, formatCurrency, mapBackendCase, stageProgress, stageSequence } from './model/workflow'
import { downloadText, paginateRows, rowsToCsv, safeLoad, safeSave, type ExceptionView, type ProfileState, type SettingsState } from './uiUtils'

const screens = ['dashboard', 'cases', 'case-details', 'document-review', 'decision', 'exceptions', 'analytics', 'settings', 'profile'] as const
type Screen = (typeof screens)[number]
const cols = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']
const heatRows = ['KYC', 'Income', 'Address', 'Credit', 'Document', 'Fraud', 'Policy']
const defaultSettings: SettingsState = { organization: 'FinFlow Demo Bank', region: 'India', currency: 'INR', timezone: 'Asia/Kolkata', language: 'English', toggles: { DocuMind: true, CreditSage: true, ComplianceGuard: true, DecisionPilot: true, ExceptionHandler: true, humanFinal: true, lowConfidence: true, complianceEscalation: true, emailAlerts: true, slaWarnings: true, auditDigest: true } }
const defaultProfile: ProfileState = { name: 'Atchayam Demo Officer', email: 'demo@finflow.local', phone: '+91 synthetic', role: 'Senior Loan Officer', prefs: { compactTables: true, darkAlerts: true, dailySummary: true } }

function App() {
  const [authed, setAuthed] = useState(false)
  const [theme, setTheme] = useState<'dark' | 'light'>(() => safeLoad('finflow-theme', 'dark'))
  const [screen, setScreen] = useState<Screen>('dashboard')
  const [query, setQuery] = useState('')
  const [stageFilter, setStageFilter] = useState<CaseStage | 'all'>('all')
  const [riskFilter, setRiskFilter] = useState<RiskBand | 'all'>('all')
  const [assigneeFilter, setAssigneeFilter] = useState('all')
  const [page, setPage] = useState(1)
  const [selectedId, setSelectedId] = useState('')
  const [status, setStatus] = useState('Mock providers ready')
  const [loading, setLoading] = useState(false)
  const [uiError, setUiError] = useState('')
  const [backendCases, setBackendCases] = useState<BackendCase[]>([])
  const [events, setEvents] = useState<BackendEvent[]>([])
  const [exceptions, setExceptions] = useState<Array<Record<string, unknown>>>([])
  const [exceptionStatus, setExceptionStatus] = useState<Record<string, string>>({})
  const [analytics, setAnalytics] = useState<AnalyticsSummary | null>(null)
  const [caseDrafts, setCaseDrafts] = useState<Record<string, Partial<LoanCase>>>({})
  const [editingCase, setEditingCase] = useState(false)
  const [menu, setMenu] = useState<'search' | 'notifications' | 'avatar' | 'filters' | 'case-actions' | 'history' | null>(null)
  const [settings, setSettings] = useState<SettingsState>(() => safeLoad('finflow-settings', defaultSettings))
  const [savedSettings, setSavedSettings] = useState(settings)
  const [settingsSaved, setSettingsSaved] = useState('')
  const [profile, setProfile] = useState<ProfileState>(() => safeLoad('finflow-profile', defaultProfile))
  const [profileEdit, setProfileEdit] = useState(false)
  const [permissionsOpen, setPermissionsOpen] = useState(false)

  useEffect(() => { safeSave('finflow-theme', theme) }, [theme])
  async function refresh(nextId = selectedId) {
    setLoading(true); setUiError('')
    try {
      const [caseRows, summary, exceptionRowsRaw] = await Promise.all([listCases(), getAnalytics(), getExceptions()])
      setBackendCases(caseRows); setAnalytics(summary); setExceptions(exceptionRowsRaw)
      const target = nextId || caseRows[0]?.id || ''
      setSelectedId(target)
      if (target) setEvents(await getEvents(target))
      setStatus(`Live API synced: ${caseRows.length} case(s)`)
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Backend unavailable; showing synthetic reference data'
      setUiError(message); setStatus(message)
    } finally { setLoading(false) }
  }
  // eslint-disable-next-line react-hooks/set-state-in-effect, react-hooks/exhaustive-deps
  useEffect(() => { void refresh() }, [])

  const hasLive = backendCases.length > 0
  const liveCases = backendCases.map(mapBackendCase)
  const viewCases = useMemo(() => expandCases(liveCases, hasLive).map((item) => ({ ...item, ...caseDrafts[item.backendId ?? item.id] })), [liveCases, hasLive, caseDrafts])
  const localExceptions = useMemo(() => exceptionRows(exceptions, viewCases).map((row) => ({ ...row, status: exceptionStatus[row.id] ?? row.status })), [exceptions, viewCases, exceptionStatus])
  const searched = useMemo(() => filterCases(viewCases, { query, stage: stageFilter }), [query, stageFilter, viewCases])
  const cases = searched.filter((item) => (riskFilter === 'all' || item.riskBand === riskFilter) && (assigneeFilter === 'all' || item.assignedTo === assigneeFilter))
  const pagedCases = paginateRows(cases, page, 12)
  const selected = cases.find((item) => item.backendId === selectedId || item.id === selectedId) ?? cases[0] ?? demoCases[0]
  const selectedBackendId = selected.backendId ?? backendCases[0]?.id ?? ''
  const selectedException = localExceptions.find((item) => item.id === selectedId) ?? localExceptions[0]
  const metrics = buildDashboardMetrics(viewCases)
  const selectCase = (item: LoanCase, next: Screen = 'case-details') => { setSelectedId(item.backendId ?? item.id); setScreen(next) }
  const logout = () => { setAuthed(false); setSelectedId(''); setMenu(null) }
  const updateCase = (patch: Partial<LoanCase>) => setCaseDrafts((drafts) => ({ ...drafts, [selected.backendId ?? selected.id]: { ...drafts[selected.backendId ?? selected.id], ...patch } }))
  const saveSettings = () => { safeSave('finflow-settings', settings); setSavedSettings(settings); setSettingsSaved('Saved locally') }
  const saveProfile = () => { safeSave('finflow-profile', profile); setProfileEdit(false) }

  async function createDemoCase(profileType: 'strong' | 'weak' = 'strong') {
    const payload = profileType === 'strong'
      ? { applicant_name: 'Priya Sharma', loan_type: 'personal', loan_amount: 500000, tenure_months: 36, monthly_income: 125000 }
      : { applicant_name: 'Watch Listed', loan_type: 'personal', loan_amount: 3000000, tenure_months: 36, monthly_income: 45000 }
    const created = await postJson<BackendCase>('/cases', payload)
    await refresh(created.id); return created.id
  }
  async function runE2EDemo(profileType: 'strong' | 'weak' = 'strong') {
    setStatus(`Running ${profileType} case workflow...`)
    try {
      const id = await createDemoCase(profileType)
      await postJson(`/cases/${id}/run/documents`, {})
      await submitDocumentDecision(id, 'APPROVE_DOCS', 'Synthetic masked field reviewed.', false)
      for (const step of ['verification', 'credit', 'compliance', 'decision']) await postJson(`/cases/${id}/run/${step}`, {})
      await submitLoanDecision(id, profileType === 'weak' ? 'refer' : 'approve', false)
      await refresh(id); setStatus(`Backend case ${id.slice(0, 8).toUpperCase()} completed`)
    } catch (error) { setStatus(error instanceof Error ? error.message : 'Backend workflow unavailable') }
  }
  async function submitDocumentDecision(id = selectedBackendId, decision = 'APPROVE_DOCS', notes = '', doRefresh = true) {
    if (!id) return
    await postJson('/webhooks/action-center', { case_id: id, task_type: 'document_review', decision, reviewer: 'demo.officer', reason: notes || 'Synthetic document review action recorded.' })
    if (doRefresh) await refresh(id)
  }
  async function submitLoanDecision(id = selectedBackendId, decision = 'approve', doRefresh = true) {
    if (!id) return
    await postJson('/webhooks/action-center', { case_id: id, task_type: 'final_decision', decision, reviewer: 'demo.officer', reason: `Officer selected ${decision} after reviewing mock provider evidence.` })
    if (doRefresh) await refresh(id)
  }
  if (!authed) return <Login theme={theme} setTheme={setTheme} onLogin={() => setAuthed(true)} />

  return <main className={`app ${theme}`}><Sidebar screen={screen} setScreen={setScreen} logout={logout} /><section className="workspace ui-shell">{loading && <div className="loading-bar" />}<Topbar screen={screen} theme={theme} setTheme={setTheme} menu={menu} setMenu={setMenu} query={query} setQuery={(value) => { setQuery(value); setScreen('cases') }} logout={logout} setScreen={setScreen} /><StatusRail status={status} analytics={analytics} error={uiError} onRun={runE2EDemo} />
    {screen === 'dashboard' && <Dashboard metrics={metrics} analytics={analytics} hasLive={hasLive} cases={viewCases} events={events} exceptions={exceptions} onSelect={selectCase} />}
    {screen === 'cases' && <Cases cases={cases} pagedCases={pagedCases} selected={selected} query={query} stageFilter={stageFilter} riskFilter={riskFilter} assigneeFilter={assigneeFilter} page={page} setPage={setPage} setQuery={setQuery} setStageFilter={setStageFilter} setRiskFilter={setRiskFilter} setAssigneeFilter={setAssigneeFilter} menu={menu} setMenu={setMenu} onSelect={(item) => selectCase(item, 'cases')} onCreate={createDemoCase} onExport={() => downloadText('finflow-cases.csv', rowsToCsv(cases))} onReview={() => selectCase(selected, selected.hasException ? 'document-review' : 'case-details')} />}
    {screen === 'case-details' && <CaseDetails caseItem={selected} events={events} editing={editingCase} setEditing={setEditingCase} updateCase={updateCase} openMenu={() => setMenu(menu === 'case-actions' ? null : 'case-actions')} menuOpen={menu === 'case-actions'} goDecision={() => setScreen('decision')} goExceptions={() => setScreen('exceptions')} />}
    {screen === 'document-review' && <DocumentReview caseItem={selected} cases={cases} onDecision={submitDocumentDecision} onClose={() => setScreen('case-details')} onMove={(dir) => selectCase(moveCase(cases, selected, dir), 'document-review')} />}
    {screen === 'decision' && <Decision caseItem={selected} events={events} historyOpen={menu === 'history'} setHistoryOpen={(open) => setMenu(open ? 'history' : null)} onDecision={submitLoanDecision} />}
    {screen === 'exceptions' && <Exceptions exceptions={localExceptions} selected={selectedException} setSelected={(id) => setSelectedId(id)} updateStatus={(id, nextStatus) => setExceptionStatus((rows) => ({ ...rows, [id]: nextStatus }))} />}
    {screen === 'analytics' && <Analytics analytics={analytics} cases={viewCases} exceptions={exceptions} hasLive={hasLive} />}
    {screen === 'settings' && <SettingsView settings={settings} setSettings={setSettings} saved={settingsSaved} onSave={saveSettings} onDiscard={() => { setSettings(savedSettings); setSettingsSaved('Discarded local edits') }} />}
    {screen === 'profile' && <Profile events={events} profile={profile} setProfile={setProfile} editing={profileEdit} setEditing={setProfileEdit} saveProfile={saveProfile} permissionsOpen={permissionsOpen} setPermissionsOpen={setPermissionsOpen} />}
  </section></main>
}

function Login({ theme, setTheme, onLogin }: { theme: string; setTheme: (theme: 'dark' | 'light') => void; onLogin: () => void }) {
  const [email, setEmail] = useState(import.meta.env.VITE_DEMO_EMAIL ?? 'demo@finflow.local')
  const [password, setPassword] = useState(import.meta.env.VITE_DEMO_PASSWORD ?? 'finflow-demo')
  const [error, setError] = useState('')
  function submit(note = '') { if (email.includes('@') && password.length >= 6) { setError(note); onLogin() } else setError('Use the demo login shown in this screen.') }
  return <main className={`login ${theme}`}><section className="login-panel"><Brand /><h1>Sign in</h1><p>Demo login for the local mock provider workspace.</p><label>Email<input aria-label="Email" value={email} onChange={(e) => setEmail(e.target.value)} /></label><label>Password<input aria-label="Password" value={password} onChange={(e) => setPassword(e.target.value)} type="password" /></label><div className="login-row"><span><CheckCircle2 size={16} /> Demo mode</span><button className="text-btn" title="Mock auth only; no real identity provider is contacted">Mock auth only</button></div>{error && <span className="form-error">{error}</span>}<button className="primary" onClick={() => submit()}><LockKeyhole size={18} /> Secure access</button><button className="secondary" onClick={() => submit('Simulated SSO login') }><ShieldCheck size={18} /> Sign in with SSO</button><div className="trust"><ShieldCheck /><strong>Audit ready</strong><span>Simulated UiPath client, synthetic data only</span></div><button className="theme-link" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>Switch theme</button></section><section className="login-visual"><div className="auth-ring"><ShieldCheck size={130} /></div><div className="login-float top"><b>Human approval gate</b><span>Action Center task preview</span></div><div className="login-float bottom"><b>Mock provider chain</b><span>DocuMind - CreditSage - ComplianceGuard</span></div></section></main>
}

function Dashboard({ metrics, analytics, hasLive, cases, events, exceptions, onSelect }: { metrics: ReturnType<typeof buildDashboardMetrics>; analytics: AnalyticsSummary | null; hasLive: boolean; cases: LoanCase[]; events: BackendEvent[]; exceptions: Array<Record<string, unknown>>; onSelect: (item: LoanCase, next?: Screen) => void }) {
  const approvalRate = cases.length ? `${Math.round((metrics.completed / cases.length) * 100)}%` : '0%'
  const kpis = [{ icon: <BriefcaseBusiness />, label: 'Active cases', value: metrics.activeCases, delta: hasLive ? 'live case state' : 'synthetic fallback' }, { icon: <FileCheck2 />, label: 'Pending review', value: metrics.humanApprovals, delta: 'derived from status' }, { icon: <CheckCircle2 />, label: 'Completion', value: approvalRate, delta: 'derived locally', tone: 'green' }, { icon: <AlertTriangle />, label: 'Exceptions', value: metrics.exceptions, delta: 'live or synthetic', tone: 'amber' }, { icon: <Clock3 />, label: 'Avg cycle time', value: hasLive ? 'N/A' : '3.7d', delta: hasLive ? 'not exposed by API' : 'synthetic' }, { icon: <BarChart3 />, label: 'Approval rate', value: approvalRate, delta: analytics ? 'analytics summary' : 'synthetic', tone: 'green' }]
  return <div className="ui-grid dashboard-dense"><div className="stat-row">{kpis.map((kpi) => <StatTile key={kpi.label} {...kpi} />)}</div><PipelineTable cases={cases.slice(0, 8)} onSelect={onSelect} /><Panel title="SLA risk"><Donut label="At risk" value={metrics.exceptions} segments={[{ label: 'Open', value: metrics.exceptions || 1, tone: 'amber' }, { label: 'Awaiting human', value: metrics.humanApprovals || 1, tone: 'red' }, { label: 'Closed', value: metrics.completed || 1, tone: 'green' }]} /></Panel><AgentActivity events={events} /><ApprovalQueue cases={cases.filter((c) => c.needsHumanApproval).slice(0, 5)} onSelect={onSelect} /><Panel title="Exceptions"><Heatmap rows={heatRows} cols={cols} cells={heatCells(exceptions.length)} /></Panel><CaseInsights hasLive={hasLive} /></div>
}

function Cases(props: { cases: LoanCase[]; pagedCases: LoanCase[]; selected: LoanCase; query: string; stageFilter: CaseStage | 'all'; riskFilter: RiskBand | 'all'; assigneeFilter: string; page: number; setPage: (n: number) => void; setQuery: (q: string) => void; setStageFilter: (s: CaseStage | 'all') => void; setRiskFilter: (r: RiskBand | 'all') => void; setAssigneeFilter: (a: string) => void; menu: string | null; setMenu: (m: 'filters' | null) => void; onSelect: (item: LoanCase) => void; onCreate: (p?: 'strong' | 'weak') => void; onExport: () => void; onReview: () => void }) {
  const pages = Math.max(1, Math.ceil(props.cases.length / 12))
  return <div className="cases-layout"><section className="panel table-card"><div className="filterbar"><div className="search"><Search size={18} /><input aria-label="Search cases" value={props.query} onChange={(e) => { props.setQuery(e.target.value); props.setPage(1) }} placeholder="Search cases, customers, products" /></div><button aria-label="Open case filters" onClick={() => props.setMenu(props.menu === 'filters' ? null : 'filters')}><Filter size={16} /> Filters</button><button onClick={props.onExport}><Download size={16} /> Export</button><button onClick={() => void props.onCreate('strong')}>New strong case</button><button onClick={() => void props.onCreate('weak')}>New weak case</button></div>{props.menu === 'filters' && <FilterPopover {...props} />}<div className="chipbar">{(['all', ...stageSequence.map((s) => s.id)] as Array<CaseStage | 'all'>).map((stage) => <button aria-label={`Filter ${stage}`} className={props.stageFilter === stage ? 'chip active' : 'chip'} key={stage} onClick={() => { props.setStageFilter(stage); props.setPage(1) }}>{stage === 'all' ? 'All stages' : label(stage)}</button>)}</div><DenseCaseTable cases={props.pagedCases} onSelect={props.onSelect} /><footer className="table-footer"><span>Showing {props.pagedCases.length ? (props.page - 1) * 12 + 1 : 0}-{Math.min(props.page * 12, props.cases.length)} of {props.cases.length}</span><div><button disabled={props.page === 1} onClick={() => props.setPage(Math.max(1, props.page - 1))}>Prev</button>{[1, 2].filter((p) => p <= pages).map((p) => <button className={props.page === p ? 'active' : ''} key={p} onClick={() => props.setPage(p)}>{p}</button>)}<button disabled={props.page === pages} onClick={() => props.setPage(Math.min(pages, props.page + 1))}>Next</button></div></footer></section><CaseDrawer caseItem={props.selected} onReview={props.onReview} /></div>
}

function CaseDetails({ caseItem, events, editing, setEditing, updateCase, openMenu, menuOpen, goDecision, goExceptions }: { caseItem: LoanCase; events: BackendEvent[]; editing: boolean; setEditing: (v: boolean) => void; updateCase: (p: Partial<LoanCase>) => void; openMenu: () => void; menuOpen: boolean; goDecision: () => void; goExceptions: () => void }) {
  return <div className="details-dense"><HeaderCard caseItem={caseItem} actions={<><button onClick={() => setEditing(!editing)}>Edit case</button><button aria-label="More case actions" onClick={openMenu}><MoreVertical size={16} /></button>{menuOpen && <div className="popover menu-pop"><button onClick={goDecision}>Open decision</button><button onClick={goExceptions}>View exceptions</button></div>}</>} />{editing && <Panel title="Edit case"><FormGrid items={[['Name', caseItem.applicantName], ['Amount', String(caseItem.amount)], ['Tenure', '36']]} onChange={(labelText, value) => labelText === 'Name' ? updateCase({ applicantName: value }) : labelText === 'Amount' ? updateCase({ amount: Number(value) || caseItem.amount }) : null} /></Panel>}<StageStepper caseItem={caseItem} /><Panel title="Documents & extraction"><DocsList /></Panel><Panel title="Credit profile"><Gauge score={caseItem.creditScore ?? 742} band={caseItem.riskBand} /><SignalGrid caseItem={caseItem} /></Panel><Panel title="Compliance checks"><Checklist rows={['AML screening passed', 'KYC consistency checked', 'RBI exposure within mock policy']} flagged={caseItem.compliancePassed === false} /></Panel><SignalStrip caseItem={caseItem} /><Timeline events={events} /><Panel title="Next action"><p>{caseItem.needsHumanApproval ? 'Human review is waiting in Action Center.' : 'Agents can continue the next stage.'}</p><button className="primary" onClick={goDecision}>Open decision center</button></Panel></div>
}

function DocumentReview({ caseItem, cases, onDecision, onClose, onMove }: { caseItem: LoanCase; cases: LoanCase[]; onDecision: (id?: string, decision?: string, notes?: string) => void; onClose: () => void; onMove: (d: -1 | 1) => void }) {
  const [decision, setDecision] = useState('APPROVE_DOCS'); const [notes, setNotes] = useState('Synthetic masked field reviewed.')
  return <div className="review-dense"><HeaderCard caseItem={caseItem} actions={<><button onClick={onClose}>Close review</button><button disabled={cases.length < 2} onClick={() => onMove(-1)}>Previous</button><button disabled={cases.length < 2} onClick={() => onMove(1)}>Next</button></>} /><Panel title="Flagged documents"><FlaggedDocs /></Panel><section className="panel synthetic-viewer"><b>SYNTHETIC DOCUMENT VIEWER</b><span>No real identity replica rendered</span><div className="synthetic-page"><i /><i /><i /><i /></div></section><Panel title="Extraction confidence"><Donut label="Confidence" value="72%" segments={[{ label: 'Matched fields', value: 72, tone: 'teal' }, { label: 'Needs review', value: 28, tone: 'amber' }]} /><ExtractedFields /></Panel><section className="panel decision-panel"><h2>Review decision</h2>{['APPROVE_DOCS', 'REQUEST_RESUBMIT', 'ESCALATE'].map((option) => <label key={option}><input name="doc-review-decision" type="radio" checked={decision === option} onChange={() => setDecision(option)} />{label(option.toLowerCase())}</label>)}<label>Reviewer notes<textarea value={notes} onChange={(e) => setNotes(e.target.value)} /></label><button className="primary" onClick={() => void onDecision(undefined, decision, notes)}>Submit review</button><button className="secondary" onClick={() => void onDecision(undefined, 'REQUEST_RESUBMIT', notes)}>Request documents</button></section></div>
}

function Decision({ caseItem, events, historyOpen, setHistoryOpen, onDecision }: { caseItem: LoanCase; events: BackendEvent[]; historyOpen: boolean; setHistoryOpen: (v: boolean) => void; onDecision: (id?: string, decision?: string) => void }) {
  const report = () => downloadText(`finflow-${caseItem.id}-summary.txt`, `Synthetic FinFlow summary\nCase: ${caseItem.id}\nApplicant: ${caseItem.applicantName}\nRecommendation: ${caseItem.recommendation || 'REFER'}\nProvider: mock provider`)
  return <div className="decision-dense"><HeaderCard caseItem={caseItem} actions={<><button onClick={() => setHistoryOpen(!historyOpen)}>Case history</button><button onClick={report}><Download size={16} /> Report</button></>} /><Panel title="Credit profile"><Gauge score={caseItem.creditScore ?? 742} band={caseItem.riskBand} /><SignalGrid caseItem={caseItem} /></Panel><Panel title="Risk assessment"><RiskFactors caseItem={caseItem} /></Panel><Panel title="Compliance cleared"><Checklist rows={['AML mock check', 'KYC synthetic match', 'RBI policy guardrail']} flagged={caseItem.compliancePassed === false} /></Panel><Panel title="Policy & conditions"><Checklist rows={['DTI threshold reviewed', 'Income stability scored', 'Reduced exposure condition available']} flagged={caseItem.riskBand === 'HIGH'} /></Panel><Panel title="Key rationale"><ul className="dense-list"><li>Recommendation is deterministic; narrative is explanation-only.</li><li>Mock bureau and compliance providers are visible in the audit trail.</li><li>Human officer remains the final decision maker.</li></ul></Panel><section className="panel ai-card"><h2>AI recommendation</h2><Chip tone={caseItem.recommendation === 'REJECT' ? 'warn' : 'ok'}>{caseItem.recommendation || 'REFER'}</Chip><b>{caseItem.recommendation === 'REJECT' ? formatCurrency(0) : formatCurrency(Math.round(caseItem.amount * 0.82))}</b><span>Confidence 84% - synthetic recommendation label</span><div className="button-row"><button className="primary" onClick={() => void onDecision(undefined, 'approve')}>Approve</button><button onClick={() => void onDecision(undefined, 'reject')}>Reject</button><button onClick={() => void onDecision(undefined, 'refer')}>Refer</button></div></section><Panel title="Documents considered"><MiniTable rows={['PAN synthetic placeholder', 'Masked Aadhaar placeholder', 'Salary slip synthetic']} /></Panel>{historyOpen && <Timeline events={events} />}<Panel title="Audit information"><Field label="Model" value="deterministic-policy-v1" /><Field label="Provider" value="mock provider" /><Field label="UiPath" value="simulated client" /></Panel></div>
}

function Exceptions({ exceptions, selected, setSelected, updateStatus }: { exceptions: ExceptionView[]; selected?: ExceptionView; setSelected: (id: string) => void; updateStatus: (id: string, status: string) => void }) {
  const [filters, setFilters] = useState({ type: 'all', severity: 'all', stage: 'all', status: 'all' })
  const rows = exceptions.filter((row) => ['type', 'severity', 'stage', 'status'].every((key) => filters[key as keyof typeof filters] === 'all' || row[key as keyof ExceptionView] === filters[key as keyof typeof filters]))
  const kpi = (status: string) => status === 'total' ? exceptions.length : exceptions.filter((row) => row.status === status).length
  const active = selected ?? rows[0]
  return <div className="exceptions-dense"><div className="stat-row">{['total', 'open', 'in_review', 'auto_resolved', 'escalated', 'resolved'].map((x, i) => <StatTile key={x} icon={<AlertTriangle />} label={label(x)} value={kpi(x)} delta="local queue state" tone={i > 3 ? 'green' : 'amber'} />)}</div><section className="panel table-card"><div className="filterbar">{(['type', 'severity', 'stage', 'status'] as const).map((key) => <button key={key} onClick={() => setFilters((f) => ({ ...f, [key]: f[key] === 'all' ? (rows[0]?.[key] ?? 'all') : 'all' }))}>{label(key)}: {filters[key]}</button>)}<button onClick={() => setFilters({ type: 'all', severity: 'all', stage: 'all', status: 'all' })}><CalendarDays size={16} /> Clear date</button></div><ExceptionTable rows={rows} selectedId={active?.id} onSelect={setSelected} /></section><section className="panel drawer"><h2>Exception detail</h2>{active ? <><Field label="ID" value={active.id} /><Field label="Case" value={active.caseId} /><Field label="Customer" value={active.customer} /><Field label="Description" value={active.description} /><BarsH rows={[{ label: 'Auto retry', value: 2 }, { label: 'Human review', value: 4, tone: 'amber' }, { label: 'Escalation', value: active.status === 'escalated' ? 3 : 1, tone: 'red' }]} /><MiniTable rows={['Created locally from live exception feed', `Current status: ${active.status}`, `Severity: ${active.severity}`]} /><div className="button-row"><button onClick={() => updateStatus(active.id, 'escalated')}>Escalate</button><button onClick={() => updateStatus(active.id, 'in_review')}>Reassign</button><button className="primary" onClick={() => updateStatus(active.id, 'resolved')}>Resolve</button></div></> : <EmptyState text="No exceptions match current filters." />}</section></div>
}

function Analytics({ analytics, cases, exceptions, hasLive }: { analytics: AnalyticsSummary | null; cases: LoanCase[]; exceptions: Array<Record<string, unknown>>; hasLive: boolean }) {
  const approvalRate = cases.length ? `${Math.round((cases.filter((c) => c.status === 'approved').length / cases.length) * 100)}%` : '0%'
  return <div className="analytics-dense"><div className="stat-row">{[{ l: 'Total cases', v: analytics?.total_cases ?? cases.length }, { l: 'Approval rate', v: approvalRate }, { l: 'Avg cycle time', v: hasLive ? 'N/A' : '3.7d' }, { l: 'Exception rate', v: `${Math.round((exceptions.length / Math.max(cases.length, 1)) * 100)}%` }, { l: 'Automation savings', v: hasLive ? 'N/A' : '82h' }].map((k) => <StatTile key={k.l} icon={<BarChart3 />} label={k.l} value={k.v} delta={hasLive ? 'derived/labeled' : 'synthetic'} />)}</div><Panel title="Loan throughput trend"><LineTrend label="Loan throughput" points={[18, 24, 22, 31, 38, 35, 44, 49]} /></Panel><Panel title="Cycle time trend"><LineTrend label="Cycle time" points={[5.2, 4.9, 4.5, 4.2, 3.9, 3.7, 3.6]} /></Panel><Panel title="Stage bottlenecks"><BarsH rows={Object.entries(analytics?.stage_counts ?? { intake: 2, verification: 4, credit: 3, compliance: 2, decision: 5 }).map(([rowLabel, value]) => ({ label: rowLabel, value: Number(value) }))} /></Panel><Panel title="Risk distribution"><Donut label="Risk" value="Mix" segments={[{ label: 'Low', value: cases.filter((c) => c.riskBand === 'LOW').length || 1, tone: 'green' }, { label: 'Medium', value: cases.filter((c) => c.riskBand === 'MEDIUM').length || 1, tone: 'amber' }, { label: 'High', value: cases.filter((c) => ['HIGH', 'VERY_HIGH'].includes(c.riskBand)).length || 1, tone: 'red' }]} /></Panel><Panel title="Automation savings"><BarsH rows={[{ label: 'Docs', value: 42 }, { label: 'Credit', value: 31 }, { label: 'Compliance', value: 24 }, { label: 'Decision', value: 18 }]} /></Panel><Panel title="Compliance audit summary"><SignalGrid caseItem={cases[0] ?? demoCases[0]} /></Panel><Panel title="Exception breakdown"><Donut label="Exceptions" value={exceptions.length || 6} segments={[{ label: 'Docs', value: 3, tone: 'amber' }, { label: 'KYC', value: 1, tone: 'red' }, { label: 'Policy', value: 2, tone: 'teal' }]} /></Panel></div>
}

function SettingsView({ settings, setSettings, saved, onSave, onDiscard }: { settings: SettingsState; setSettings: (s: SettingsState) => void; saved: string; onSave: () => void; onDiscard: () => void }) {
  const update = (key: keyof SettingsState, value: string) => setSettings({ ...settings, [key]: value })
  const toggle = (key: string) => setSettings({ ...settings, toggles: { ...settings.toggles, [key]: !settings.toggles[key] } })
  return <div className="settings-dense"><header className="settings-head"><h2>Workspace settings</h2><div><button onClick={onDiscard}>Discard</button><button className="primary" onClick={onSave}>Save changes</button></div>{saved && <small>{saved}</small>}</header><Panel title="Workspace"><FormGrid items={[['Organization', settings.organization], ['Region', settings.region], ['Currency', settings.currency], ['Timezone', settings.timezone], ['Language', settings.language]]} onChange={(k, v) => update(k.toLowerCase() as keyof SettingsState, v)} /></Panel><Panel title="UiPath connection"><Field label="Status" value="simulated client" /><Field label="Endpoint" value="configured by env" /><Field label="Mode" value="MOCK" /></Panel><Panel title="Agents">{['DocuMind', 'CreditSage', 'ComplianceGuard', 'DecisionPilot', 'ExceptionHandler'].map((x) => <Toggle key={x} label={x} checked={settings.toggles[x]} onChange={() => toggle(x)} />)}</Panel><Panel title="Workflow rules">{[['humanFinal', 'Require human final decision'], ['lowConfidence', 'Route low confidence docs'], ['complianceEscalation', 'Escalate critical compliance flags']].map(([k, text]) => <Toggle key={k} label={text} checked={settings.toggles[k]} onChange={() => toggle(k)} />)}</Panel><Panel title="Notifications">{[['emailAlerts', 'Email queue alerts'], ['slaWarnings', 'SLA breach warnings'], ['auditDigest', 'Daily audit digest']].map(([k, text]) => <Toggle key={k} label={text} checked={settings.toggles[k]} onChange={() => toggle(k)} />)}</Panel><Panel title="Audit logging"><Field label="Retention" value="Synthetic local audit retained in SQLite" /><Field label="Webhook auth" value="bypassed only in local mock mode" /></Panel></div>
}

function Profile({ events, profile, setProfile, editing, setEditing, saveProfile, permissionsOpen, setPermissionsOpen }: { events: BackendEvent[]; profile: ProfileState; setProfile: (p: ProfileState) => void; editing: boolean; setEditing: (v: boolean) => void; saveProfile: () => void; permissionsOpen: boolean; setPermissionsOpen: (v: boolean) => void }) {
  const pref = (key: string) => setProfile({ ...profile, prefs: { ...profile.prefs, [key]: !profile.prefs[key] } })
  return <div className="profile-dense"><section className="panel profile-hero"><div className="big-avatar">AM</div><div><h2>{profile.name}</h2><Chip>{profile.role}</Chip><p><Mail size={14} /> {profile.email} <Phone size={14} /> {profile.phone}</p></div><button onClick={() => setEditing(!editing)}>Edit profile</button></section>{editing && <Panel title="Edit profile"><FormGrid items={[['Name', profile.name], ['Email', profile.email], ['Phone', profile.phone], ['Role', profile.role]]} onChange={(k, v) => setProfile({ ...profile, [k.toLowerCase()]: v })} /><button className="primary" onClick={saveProfile}>Save profile</button></Panel>}<Panel title="Role & permissions"><Field label="Role" value="Credit Analyst" /><Field label="Scope" value="Retail loan cases" /><button onClick={() => setPermissionsOpen(!permissionsOpen)}>View permissions</button>{permissionsOpen && <MiniTable rows={['Approve low-risk cases', 'Resolve document exceptions', 'Refer credit committee cases']} />}</Panel><Panel title="Approval authority"><Gauge score={760} band="LOW" /><Field label="Per-case limit" value={formatCurrency(2000000)} /></Panel><Panel title="Security"><Checklist rows={['MFA enabled', 'Trusted device registered', 'Account active']} /></Panel><Panel title="Team & branch"><Field label="Branch" value="Digital Lending" /><Field label="Team" value="Loan Operations" /></Panel><Panel title="Audit signature"><Field label="Signature" value="AM-FINFLOW-DEMO" /><Field label="Mode" value="synthetic local demo" /></Panel><Timeline events={events} /><Panel title="Preferences">{[['compactTables', 'Compact tables'], ['darkAlerts', 'Dark theme alerts'], ['dailySummary', 'Daily queue summary']].map(([k, text]) => <Toggle key={k} label={text} checked={profile.prefs[k]} onChange={() => pref(k)} />)}</Panel></div>
}

function Sidebar({ screen, setScreen, logout }: { screen: Screen; setScreen: (screen: Screen) => void; logout: () => void }) { return <aside className="sidebar"><Brand /><nav>{screens.map((item) => <button className={screen === item ? 'active' : ''} key={item} onClick={() => setScreen(item)}>{navIcon(item)}<span>{label(item)}</span></button>)}</nav><footer className="sidebar-footer"><button onClick={() => setScreen('profile')}><UserRound size={18} /> Profile</button><button onClick={logout}><LockKeyhole size={18} /> Logout</button></footer></aside> }
function Topbar({ screen, theme, setTheme, menu, setMenu, query, setQuery, logout, setScreen }: { screen: Screen; theme: 'dark' | 'light'; setTheme: (theme: 'dark' | 'light') => void; menu: string | null; setMenu: (menu: 'search' | 'notifications' | 'avatar' | null) => void; query: string; setQuery: (query: string) => void; logout: () => void; setScreen: (screen: Screen) => void }) { return <header className="topbar"><div><p className="eyebrow">UiPath-ready orchestration boundary</p><h1>{label(screen)}</h1></div><div className="top-actions"><button aria-label="Open global search" className="icon-btn" onClick={() => setMenu(menu === 'search' ? null : 'search')}><Search size={18} /></button>{menu === 'search' && <div className="popover top-pop"><label>Search cases<input value={query} onChange={(e) => setQuery(e.target.value)} autoFocus /></label></div>}<button aria-label="Toggle theme" className="icon-btn" onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? <Sun size={18} /> : <Moon size={18} />}</button><button aria-label="Open notifications" className="icon-btn" onClick={() => setMenu(menu === 'notifications' ? null : 'notifications')}><Bell size={18} /></button>{menu === 'notifications' && <div className="popover top-pop"><b>Synthetic notifications</b><p>3 cases approaching SLA.</p><p>Document review queue updated.</p></div>}<button aria-label="Open user menu" className="avatar" onClick={() => setMenu(menu === 'avatar' ? null : 'avatar')}>AM</button>{menu === 'avatar' && <div className="popover top-pop"><button onClick={() => { setScreen('profile'); setMenu(null) }}>Profile</button><button onClick={logout}>Logout</button></div>}</div></header> }
function StatusRail({ status, analytics, error, onRun }: { status: string; analytics: AnalyticsSummary | null; error: string; onRun: (profile?: 'strong' | 'weak') => void }) { return <section className={`status-rail ${error ? 'error' : ''}`}><span>{status}</span><span>{analytics ? `${analytics.total_cases} live case(s)` : 'Synthetic fallback available'}</span><button onClick={() => onRun('strong')}>Run approve demo <ChevronRight size={16} /></button><button onClick={() => onRun('weak')}>Run weak demo</button></section> }
function FilterPopover(props: { riskFilter: RiskBand | 'all'; assigneeFilter: string; setRiskFilter: (r: RiskBand | 'all') => void; setAssigneeFilter: (a: string) => void; setPage: (n: number) => void; cases: LoanCase[] }) { const assignees = ['all', ...Array.from(new Set(props.cases.map((c) => c.assignedTo)))] ; return <div className="popover filter-pop"><label>Risk<select value={props.riskFilter} onChange={(e) => { props.setRiskFilter(e.target.value as RiskBand | 'all'); props.setPage(1) }}>{['all', 'LOW', 'MEDIUM', 'HIGH', 'VERY_HIGH', 'UNKNOWN'].map((x) => <option key={x}>{x}</option>)}</select></label><label>Assignee<select value={props.assigneeFilter} onChange={(e) => { props.setAssigneeFilter(e.target.value); props.setPage(1) }}>{assignees.map((x) => <option key={x}>{x}</option>)}</select></label></div> }
function Panel({ title, children }: { title: string; children: ReactNode }) { return <section className="panel dense-panel"><h2>{title}</h2>{children}</section> }
function Brand() { return <div className="brand"><span>F</span><div><b>FinFlow</b><small>Loan Case Intelligence</small></div></div> }
function Chip({ children, tone = 'ok' }: { children: ReactNode; tone?: string }) { return <span className={`badge ${tone}`}>{children}</span> }
function Field({ label: fieldLabel, value }: { label: string; value: string | number }) { return <p className="field"><span>{fieldLabel}</span><b>{value}</b></p> }
function Toggle({ label: toggleLabel, checked, onChange }: { label: string; checked: boolean; onChange: () => void }) { return <label className="toggle-row"><span>{toggleLabel}</span><input type="checkbox" checked={checked} onChange={onChange} /></label> }
function HeaderCard({ caseItem, actions }: { caseItem: LoanCase; actions: ReactNode }) { return <section className="panel header-card"><div className="big-avatar">{caseItem.applicantName.slice(0, 2).toUpperCase()}</div><div><h2>{caseItem.applicantName}</h2><Chip tone={caseItem.hasException ? 'warn' : 'ok'}>{caseItem.status}</Chip></div><Field label="Amount" value={formatCurrency(caseItem.amount)} /><Field label="Product" value={caseItem.loanType} /><Field label="Tenure" value="36 months" /><div className="button-row">{actions}</div></section> }
function StageStepper({ caseItem }: { caseItem: LoanCase }) { return <section className="panel stage-stepper">{stageSequence.filter((s) => s.id !== 'exception').map((stage) => <div className={stage.id === caseItem.stage ? 'step active' : 'step'} key={stage.id}><i /><b>{stage.label}</b><span>{stage.actor}</span></div>)}</section> }
function PipelineTable({ cases, onSelect }: { cases: LoanCase[]; onSelect: (item: LoanCase, next?: Screen) => void }) { return <section className="panel pipeline-table"><h2>Active loan cases pipeline</h2><div className="stage-summary">{stageSequence.slice(0, 6).map((s) => <span key={s.id}><b>{cases.filter((c) => c.stage === s.id).length}</b>{s.label}</span>)}</div>{cases.length ? <DenseCaseTable cases={cases} onSelect={(item) => onSelect(item)} compact /> : <EmptyState text="No cases yet. Run a demo case to seed the pipeline." />}</section> }
function DenseCaseTable({ cases, onSelect, compact = false }: { cases: LoanCase[]; onSelect: (item: LoanCase) => void; compact?: boolean }) { const headers = compact ? ['Case ID', 'Customer', 'Product', 'Stage', 'SLA', 'Owner'] : ['Case ID', 'Customer', 'Product', 'Amount', 'Stage', 'Risk', 'SLA', 'Assigned', 'Agent status', 'Updated', '']; return <div className="dense-table" role="table"><div className="dense-row head" role="row">{headers.map((h) => <b key={h}>{h}</b>)}</div>{cases.map((item) => <button className="dense-row" key={item.backendId ?? item.id} onClick={() => onSelect(item)}><span>{item.id}</span><span>{item.applicantName}</span><span>{item.loanType}</span>{!compact && <span>{formatCurrency(item.amount)}</span>}<Chip>{label(item.stage)}</Chip>{!compact && <Chip tone={['HIGH', 'VERY_HIGH'].includes(item.riskBand) ? 'warn' : 'ok'}>{item.riskBand}</Chip>}<span>{item.sla}</span><span>{item.assignedTo}</span>{!compact && <span>{item.needsHumanApproval ? 'Awaiting input' : 'Completed'}</span>}{!compact && <span>{item.updated}</span>}<MoreVertical size={15} /></button>)}</div> }
function CaseDrawer({ caseItem, onReview }: { caseItem: LoanCase; onReview: () => void }) { return <aside className="panel drawer"><h2>{caseItem.id}</h2><Chip tone={caseItem.riskBand === 'HIGH' ? 'warn' : 'ok'}>{caseItem.riskBand}</Chip><Field label="Customer" value={caseItem.applicantName} /><Field label="Product" value={caseItem.loanType} /><Field label="Amount" value={formatCurrency(caseItem.amount)} /><Field label="Stage" value={label(caseItem.stage)} /><div className="mini-progress"><span style={{ width: `${stageProgress(caseItem)}%` }} /></div><Field label="SLA" value={caseItem.sla} /><Field label="Assigned" value={caseItem.assignedTo} /><button className="primary" onClick={onReview}>Review now</button></aside> }
function AgentActivity({ events }: { events: BackendEvent[] }) { const fallback = ['DocuMind extracted synthetic documents', 'CreditSage scored applications', 'ComplianceGuard flagged cases', 'DecisionPilot generated recommendations']; const rows = events.length ? events.slice(-5).map((e) => `${e.actor}: ${e.event_type}`) : fallback; return <Panel title="Agent activity (24h)">{rows.map((row) => <p className="activity-row" key={row}><span className="dot" />{row}<small>{events.length ? 'live' : 'synthetic'}</small></p>)}</Panel> }
function ApprovalQueue({ cases, onSelect }: { cases: LoanCase[]; onSelect: (item: LoanCase, next?: Screen) => void }) { const rows = cases.length ? cases : demoCases.slice(0, 5); return <Panel title="Approval queue"><MiniRows rows={rows.map((c) => [c.id, c.applicantName, label(c.stage), c.sla])} onClick={(index) => onSelect(rows[index], 'decision')} /></Panel> }
function CaseInsights({ hasLive }: { hasLive: boolean }) { return <Panel title="Case insights"><p className="insight">{hasLive ? 'Live cases synced from the backend event store.' : 'Synthetic case insights for empty backend demo mode.'}</p><p className="insight warn">SLA prioritization uses visible case status and synthetic thresholds.</p><p className="insight">Document extraction accuracy is labeled synthetic at 98.6%.</p></Panel> }
function Timeline({ events }: { events: BackendEvent[] }) { const rows = events.length ? events.map((e) => `${e.actor}: ${e.message}`) : ['Case created', 'Document exception raised', 'Human review completed', 'Decision generated']; return <Panel title="Audit trail">{rows.slice(-8).map((x) => <p className="timeline-row" key={x}>{x}</p>)}</Panel> }
function DocsList() { return <div className="doc-list">{['PAN placeholder', 'Masked Aadhaar placeholder', 'Salary slip synthetic', 'Bank statement synthetic'].map((x, i) => <p key={x}><FileCheck2 size={16} />{x}<Chip tone={i === 1 ? 'warn' : 'ok'}>{i === 1 ? '72%' : '94%'}</Chip></p>)}</div> }
function FlaggedDocs() { return <div className="doc-list">{['Aadhaar: masked field confidence 72%', 'PAN: name consistency verified', 'Salary slip: income extracted'].map((x) => <p key={x}><AlertTriangle size={16} />{x}<Chip tone="warn">review</Chip></p>)}</div> }
function ExtractedFields() { return <div className="extract-fields">{['Applicant name', 'PAN synthetic', 'Aadhaar last four', 'Monthly income', 'Employer'].map((x, i) => <Field key={x} label={x} value={i === 2 ? '72% confidence' : '94% confidence'} />)}</div> }
function SignalGrid({ caseItem }: { caseItem: LoanCase }) { return <div className="signal-grid"><Field label="Score" value={caseItem.creditScore ?? 742} /><Field label="DTI" value="36.9%" /><Field label="Risk" value={caseItem.riskBand} /><Field label="Active loans" value="2" /></div> }
function SignalStrip({ caseItem }: { caseItem: LoanCase }) { return <section className="panel signal-strip">{[['Income', formatCurrency(125000)], ['EMI', formatCurrency(16000)], ['DTI', '36.9%'], ['Active loans', '2'], ['DPD', '0'], ['Tenure', '36m']].map(([l, v]) => <Field key={l} label={l} value={caseItem.riskBand === 'HIGH' && l === 'DPD' ? '1' : v} />)}</section> }
function Checklist({ rows, flagged = false }: { rows: string[]; flagged?: boolean }) { return <div className="check-list">{rows.map((row, i) => <p key={row}><CheckCircle2 size={16} /><span>{row}</span><Chip tone={flagged && i === 0 ? 'warn' : 'ok'}>{flagged && i === 0 ? 'flag' : 'pass'}</Chip></p>)}</div> }
function RiskFactors({ caseItem }: { caseItem: LoanCase }) { return <div className="risk-factors"><Chip tone={caseItem.riskBand === 'HIGH' ? 'warn' : 'ok'}>{caseItem.riskBand}</Chip><BarsH rows={[{ label: 'Affordability', value: caseItem.riskBand === 'HIGH' ? 78 : 32, tone: caseItem.riskBand === 'HIGH' ? 'red' : 'teal' }, { label: 'Bureau', value: caseItem.creditScore ?? 742 }, { label: 'Compliance', value: caseItem.compliancePassed === false ? 90 : 18, tone: caseItem.compliancePassed === false ? 'red' : 'green' }]} /></div> }
function MiniTable({ rows }: { rows: string[] }) { return <div className="mini-table">{rows.map((row) => <p key={row}><span>{row}</span><Chip>synthetic</Chip></p>)}</div> }
function MiniRows({ rows, onClick }: { rows: string[][]; onClick?: (index: number) => void }) { return <div className="mini-table">{rows.map((row, i) => <button key={row.join('-')} onClick={() => onClick?.(i)}>{row.map((cell) => <span key={cell}>{cell}</span>)}</button>)}</div> }
function ExceptionTable({ rows, selectedId, onSelect }: { rows: ExceptionView[]; selectedId?: string; onSelect: (id: string) => void }) { return <div className="dense-table exception-table"><div className="dense-row head">{['ID', 'Type', 'Case', 'Customer', 'Stage', 'SLA', 'Severity', 'Status', 'Assignee', 'Actions'].map((h) => <b key={h}>{h}</b>)}</div>{rows.slice(0, 12).map((row) => <button className={`dense-row ${selectedId === row.id ? 'selected' : ''}`} key={row.id} onClick={() => onSelect(row.id)}><span>{row.id}</span><span>{row.type}</span><span>{row.caseId}</span><span>{row.customer}</span><span>{row.stage}</span><span>{row.sla}</span><Chip tone={row.severity === 'CRITICAL' ? 'warn' : 'ok'}>{row.severity}</Chip><Chip>{row.status}</Chip><span>{row.assignee}</span><MoreVertical size={15} /></button>)}</div> }
function FormGrid({ items, onChange }: { items: string[][]; onChange: (label: string, value: string) => void }) { return <div className="form-grid">{items.map(([itemLabel, value]) => <label key={itemLabel}><span>{itemLabel}</span><input value={value} onChange={(e) => onChange(itemLabel, e.target.value)} /></label>)}</div> }
function EmptyState({ text }: { text: string }) { return <div className="empty-state">{text}</div> }
function label(screen: string) { return screen.split(/[-_]/).map((x) => x[0].toUpperCase() + x.slice(1)).join(' ') }
function navIcon(screen: Screen) { const icons = { dashboard: <LayoutDashboard />, cases: <BriefcaseBusiness />, 'case-details': <Workflow />, 'document-review': <FileCheck2 />, decision: <ClipboardCheck />, exceptions: <AlertTriangle />, analytics: <BarChart3 />, settings: <SettingsIcon />, profile: <UserRound /> }; return icons[screen] }
function expandCases(base: LoanCase[], hasLive: boolean) { if (hasLive) return base; const people = ['Rohit Sharma', 'Neha Verma', 'Amit Patel', 'Sneha Iyer', 'Karan Mehta', 'Pooja Nair', 'Sanjay Singh', 'Rahul Das', 'Meera Kulkarni', 'Vivek Menon', 'Jyoti Malhotra', 'Daniel Kim']; const products = ['Personal loan', 'Home loan', 'Business loan', 'Vehicle loan', 'Working capital']; return Array.from({ length: 12 }, (_, i) => ({ ...(demoCases[i % demoCases.length]), id: `LN-2026-${(1478 - i).toString().padStart(5, '0')}`, applicantName: people[i % people.length], loanType: products[i % products.length], amount: 300000 + i * 125000, assignedTo: ['Arjun K.', 'Priya M.', 'Vikram R.', 'Sara N.'][i % 4], sla: ['1d 4h', '2d 6h', '6h 15m', '3h'][i % 4], updated: `${i * 15 + 2}m ago` })) }
function moveCase(cases: LoanCase[], selected: LoanCase, dir: -1 | 1) { const index = Math.max(0, cases.findIndex((item) => (item.backendId ?? item.id) === (selected.backendId ?? selected.id))); return cases[(index + dir + cases.length) % cases.length] ?? selected }
function heatCells(seed: number) { return heatRows.flatMap((row, r) => cols.map((col, c) => ({ row, col, value: ((r + 2) * (c + 3) + seed) % 9 }))) }
function exceptionRows(exceptions: Array<Record<string, unknown>>, cases: LoanCase[]): ExceptionView[] { const source = exceptions.length ? exceptions : Array.from({ length: 12 }, (_, i) => ({ exception_type: ['low_confidence_extraction', 'policy_breach', 'kyc_mismatch'][i % 3], severity: ['HUMAN_REQUIRED', 'CRITICAL', 'AUTO_RESOLVABLE'][i % 3], source_stage: stageSequence[i % stageSequence.length].id })); return source.map((item, i) => { const c = cases[i % cases.length] ?? demoCases[0]; return { id: `EX-${String(i + 1).padStart(3, '0')}`, type: String(item.exception_type), caseId: c.id, customer: c.applicantName, stage: String(item.source_stage ?? c.stage), sla: c.sla, severity: String(item.severity), status: i % 3 ? 'open' : 'resolved', assignee: c.assignedTo, description: 'Synthetic low-confidence extraction requires review.' } }) }

export default App
